### obtener todos los estudiantes de la tabla
GET http://localhost:4040/all

### obtener estudiante por rut
GET http://localhost:4040/12345678-9

### insertar un nuevo estudiante o nuevos estudiantes en la tabla
POST http://localhost:4040/insert

### actualizar registro de un estudiante
PUT http://localhost:4040/update

### eliminar registro de un estudiante
DELETE http://localhost:4040/delete
